## Assess various language models

In [1]:
import os
import json
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader
import copy
from datasets import Dataset
from transformers import AutoModelForCausalLM, AutoModelForSeq2SeqLM, AutoTokenizer 
from transformers import TrainingArguments, Trainer, Seq2SeqTrainer, DataCollatorForLanguageModeling, DataCollatorForSeq2Seq

In [2]:
# Set device type
device_type = 'cuda' if torch.cuda.is_available() else 'cpu'

### Load datasets

In [3]:
base_dir = os.path.dirname(os.path.realpath('__file__'))
data_dir = os.path.join(base_dir, 'data', 'text_question_answer')

print('Loading question and answer data...')
with open (os.path.join(data_dir, 'train-squad-v2.0.json'), 'r') as f:
    train_qna_raw = json.loads(f.read())


print('Place data into dataframe object...')
# Processing SQUAD data
df_train = None
ids = []
contexts = []
questions = []
answers = []
is_impossible = []
for il1, l1 in enumerate(train_qna_raw['data']):
    for il2, l2 in enumerate(l1['paragraphs']):
        for il3, l3 in enumerate(l2['qas']):
            ids.append(l3['id'])
            contexts.append(l2['context'])
            questions.append(l3['question'])
            try:
                answers.append(l3['answers'][0]['text'])
            except:
                answers.append('')
            is_impossible.append(l3['is_impossible'])
            
df_train = pd.DataFrame({'id': ids, 'context': contexts, 
                         'question': questions, 'answer': answers, 'is_impossible': is_impossible})

Loading question and answer data...
Place data into dataframe object...


In [4]:
df_train.head()

id  \
0  56be85543aeaaa14008c9063   
1  56be85543aeaaa14008c9065   
2  56be85543aeaaa14008c9066   
3  56bf6b0f3aeaaa14008c9601   
4  56bf6b0f3aeaaa14008c9602   

                                             context  \
0  Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...   
1  Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...   
2  Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...   
3  Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...   
4  Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...   

                                            question               answer  \
0           When did Beyonce start becoming popular?    in the late 1990s   
1  What areas did Beyonce compete in when she was...  singing and dancing   
2  When did Beyonce leave Destiny's Child and bec...                 2003   
3      In what city and state did Beyonce  grow up?        Houston, Texas   
4         In which decade did Beyonce become famous?           late 1990s   

   is_impossible  
0          False  
1          False  
2          False  
3          False  
4          False

### Text generation (casual language model)

In [6]:
class CreateHuggingFaceLM():
    '''
    Generic language model class using the HuggingFace Hub models
    '''
    # Initialize class variables
    def __init__(self, model, tokenizer, input_block_size, padding_length=100):
        self.padding_length = padding_length
        self.tokenizer = tokenizer
        self.model = model
        self.input_block_size = input_block_size
        self.train_default_args = ['title', 'num_train_epochs', 'optimizer', 'mlm', 
                                   'per_device_train_batch_size', 'per_device_eval_batch_size',
                                   'warmup_steps', 'weight_decay', 'logging_steps', 
                                   'output_dir', 'logging_dir', 'save_model']
        
        if self.tokenizer.pad_token is None:
            self.tokenizer.pad_token = self.model.config.eos_token_id
    
    # Embed text
    def embedding(self, text):
        token_ids = self.tokenizer.encode(text, return_tensors='pt')
        
        # Get embeddings
        if 'flan' in self.model.name_or_path: 
            emb = self.model.shared.weight[token_ids[0]] # embeddings for FLAN
        elif 'gpt2' in self.model.name_or_path: 
            emb = self.model.transformer.wte.weight[token_ids[0]] # embeddings for GPT2
            
        emb /= emb.norm(dim=1).unsqueeze(1) # normalise embedding weights
        emb_pad = torch.zeros(self.padding_length, emb.shape[1]) # Set and apply padding to embeddings
        emb_pad[:emb.shape[0], :] = emb
        
        return emb_pad
    
    # Generate text
    def predict(self, text, max_length=100, skip_special_tokens=True, show_scores=False):
        output_context = {
            'text': None,
            'scores': None,
        }
        
        input_ids = self.tokenizer.encode(text, return_tensors='pt')
        output = self.model.generate(input_ids, max_length=max_length, 
                                     pad_token_id=self.model.config.eos_token_id,
                                     num_return_sequences=1, output_scores=show_scores, 
                                     return_dict_in_generate=show_scores,
                                     renormalize_logits=show_scores)
                                          
        # Decode the output sequence
        if show_scores:
            output_context['text'] = self.tokenizer.decode(output['sequences'][0], skip_special_tokens=skip_special_tokens)
            output_context['scores'] = output['scores']
        else:
            output_context['text'] = self.tokenizer.decode(output[0], skip_special_tokens=skip_special_tokens)
        output_context['text'] = output_context['text'].replace('\n', '')
        output_context['text'] = output_context['text'].strip()
        
        return output_context
    
    # Tokenize function
    def _tokenize_function(self, examples):
        return self.tokenizer(examples['text'])
    
    # Tokenize pandas dataframe feature
    def tokenize_text(self, x, batched=False):  
        df_sample = pd.DataFrame({'text': x})
        hf_dataset = Dataset.from_pandas(df_sample)
        if batched:
            tokenized_dataset = hf_dataset.map(self._tokenize_function, batched=batched, num_proc=4)
        else:
            tokenized_dataset = hf_dataset.map(self._tokenize_function)

        return tokenized_dataset
    
    # Model training
    def fit(self, x, y, train_args={}, instruct=False):
        # Convert to tokens format from pandas dataframes
        tokenized_data = self.tokenize_text(x)
        tokenized_target = self.tokenize_text(y)
        
        # Check for missing input arguments
        assert set(list(train_args.keys())) == set(self.train_default_args), \
        f'Train args are not in the required format - missing: {", ".join(list(set(self.train_default_args) - set(list(train_args.keys()))))}'
        
        if instruct:
            print('Setting up training in sequence to sequence format...')
            tokenized_data = tokenized_data.add_column('labels', tokenized_target['input_ids']) # Create target sequence labels
            data_collator = DataCollatorForSeq2Seq(tokenizer=self.tokenizer, model=self.model) # Organise data for training
            
            # Setup training in sequence to sequence format
            training_args = TrainingArguments(
                optim=train_args['optimizer'], # model optimisation function
                num_train_epochs=train_args['num_train_epochs'], # total number of training epochs
                per_device_train_batch_size=train_args['per_device_train_batch_size'],  # batch size per device during training
                per_device_eval_batch_size=train_args['per_device_eval_batch_size'],   # batch size for evaluation
                warmup_steps=train_args['warmup_steps'], # number of warmup steps for learning rate scheduler
                weight_decay=train_args['weight_decay'], # strength of weight decay
                logging_steps=train_args['logging_steps'],
                output_dir='./results', # output directory
                logging_dir=train_args['logging_dir'], # log directory
            )

            trainer = Trainer(
                model=self.model,
                args=training_args,
                train_dataset=tokenized_data.remove_columns(['text']),
                eval_dataset=tokenized_data.remove_columns(['text']),
                data_collator=data_collator,
            )
    
        else:
            print('Setting up training in autoregressive format...')
            data_collator = DataCollatorForLanguageModeling(tokenizer=self.tokenizer, mlm=train_args['mlm']) # Organise data for training
            
            # Setup training in autoregressive format
            training_args = TrainingArguments(
                optim=train_args['optimizer'], 
                num_train_epochs=train_args['num_train_epochs'], 
                per_device_train_batch_size=train_args['per_device_train_batch_size'],
                per_device_eval_batch_size=train_args['per_device_eval_batch_size'], 
                warmup_steps=train_args['warmup_steps'], 
                weight_decay=train_args['weight_decay'], 
                logging_steps=train_args['logging_steps'],
                output_dir=train_args['output_dir'],
                logging_dir=train_args['logging_dir'], 
            )
            
            trainer = Seq2SeqTrainer(
                model=self.model,
                args=training_args,
                train_dataset=tokenized_data.remove_columns(['text']),
                eval_dataset=tokenized_data.remove_columns(['text']),
                data_collator=data_collator,
            )

        trainer.train() # Execute training
        
        if train_args['save_model']:
            trainer.save_model(f'./results/model_{train_args["title"]}') # Save trained model
                                          
# Calculate cosine similarity of two matrices    
def cosine_similarity(m1, m2):
    return F.cosine_similarity(m1.view(1, -1), m2.view(1, -1))

In [7]:
# GPT2 small
tokenizer_dgpt2 = AutoTokenizer.from_pretrained('distilgpt2', mirror='https://huggingface.co')
model_dgpt2 = AutoModelForCausalLM.from_pretrained("distilgpt2")

# Create HuggingFace LM from base HuggingFace model and tokenizer objects
model_dgpt2_train=copy.deepcopy(model_dgpt2)
lm_gpt2 = CreateHuggingFaceLM(model_dgpt2, tokenizer_dgpt2, input_block_size=10, padding_length=100)
lm_gpt2_train = CreateHuggingFaceLM(model_dgpt2_train, tokenizer_dgpt2, input_block_size=10, padding_length=100)

Using pad_token, but it is not set yet.


In [9]:
lm_gpt2.predict('hello world', show_scores=True)['scores']

(tensor([[ -6.1587,  -5.8585,  -8.0755,  ..., -15.7681, -12.8356,  -7.1570]]),
 tensor([[-10.1662,  -9.6845,  -9.8448,  ..., -17.6942, -15.0358,  -5.2994]]),
 tensor([[-14.8451,  -5.4011, -12.4950,  ..., -33.7572, -34.8521, -10.4029]]),
 tensor([[-15.3718,  -5.4762, -12.5057,  ..., -33.1928, -34.5009,  -9.8682]]),
 tensor([[-14.6399,  -4.8943, -11.0783,  ..., -30.5098, -31.7271,  -8.5576]]),
 tensor([[-14.6345,  -5.1920, -10.9806,  ..., -29.2536, -30.4836,  -7.8928]]),
 tensor([[-14.9126,  -5.9431, -11.2593,  ..., -28.4916, -29.7005,  -7.4626]]),
 tensor([[-15.0764,  -6.5687, -11.3499,  ..., -27.8648, -28.9608,  -7.1299]]),
 tensor([[-15.1187,  -6.9986, -11.2854,  ..., -27.3189, -28.2459,  -6.8514]]),
 tensor([[-15.0900,  -7.2397, -11.1368,  ..., -26.9202, -27.6835,  -6.6504]]),
 tensor([[-15.0409,  -7.4004, -10.9969,  ..., -26.6229, -27.2407,  -6.4946]]),
 tensor([[-14.9937,  -7.4935, -10.8786,  ..., -26.4740, -26.9780,  -6.4035]]),
 tensor([[-14.9631,  -7.5899, -10.7964,  ..., -26.36

In [16]:
df_train_sample = df_train.head(10).copy()

train_args = {
    'title': 'gpt2',
    'num_train_epochs' : 50,
    'mlm': False,
    'optimizer': 'adamw_torch',
    'per_device_train_batch_size': 10,
    'per_device_eval_batch_size': 10,
    'warmup_steps': 20,
    'weight_decay': 0.01,
    'logging_steps': 10,
    'output_dir': './results',
    'logging_dir': './logs',
    'save_model': True,
}

# Set training data and targets
x = df_train_sample['question']
y = df_train_sample['question']

# Train model
lm_gpt2_train.fit(x, y, train_args, instruct=False)

Map:   0%|          | 0/10 [00:00<?, ? examples/s]

Map:   0%|          | 0/10 [00:00<?, ? examples/s]

PyTorch: setting up devices
The default value for the training argument `--report_to` will change in v5 (from all installed integrations to none). In v5, you will need to use `--report_to all` to get the same behavior as now. You should start updating your code and make this info disappear :-).
***** Running training *****
  Num examples = 10
  Num Epochs = 50
  Instantaneous batch size per device = 10
  Total train batch size (w. parallel, distributed & accumulation) = 10
  Gradient Accumulation steps = 1
  Total optimization steps = 50
  Number of trainable parameters = 81912576
You're using a GPT2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.


Setting up training in autoregressive format...




Training completed. Do not forget to share your model on huggingface.co/models =)


Saving model checkpoint to ./results/model_gpt2
Configuration saved in ./results/model_gpt2/config.json
Configuration saved in ./results/model_gpt2/generation_config.json
Model weights saved in ./results/model_gpt2/pytorch_model.bin


In [13]:
lm_gpt2.predict('When did')['text']

Generate config GenerationConfig {
  "bos_token_id": 50256,
  "eos_token_id": 50256,
  "transformers_version": "4.26.1"
}



'When did you know that the first time you saw a woman in a car, you were shocked to find that she was wearing a black dress.'

In [14]:
lm_gpt2_train.predict('When did', max_length=50)['text']

Generate config GenerationConfig {
  "bos_token_id": 50256,
  "eos_token_id": 50256,
  "transformers_version": "4.26.1"
}



'When did Beyonce start becoming popular? Beyonce was born? Beyonce was born in the U.S. and raised in the U.S. and was raised in the UK? Beyonce was a singer? Beyonce was a singer?'

In [257]:
# FLAN T5 base
tokenizer_flan = AutoTokenizer.from_pretrained('google/flan-t5-base', mirror='https://huggingface.co')
model_flan = AutoModelForSeq2SeqLM.from_pretrained('google/flan-t5-base')

model_flan_train=copy.deepcopy(model_flan)
lm_flan = CreateHuggingFaceLM(model_flan, tokenizer_flan, input_block_size=10, padding_length=200)
lm_flan_train = CreateHuggingFaceLM(model_flan_train, tokenizer_flan, input_block_size=10, padding_length=200)

loading file spiece.model from cache at /Users/williamzheng/.cache/huggingface/hub/models--google--flan-t5-base/snapshots/c782cba52f8ea6a704240578055cf1c3fc2f2ca9/spiece.model
loading file tokenizer.json from cache at /Users/williamzheng/.cache/huggingface/hub/models--google--flan-t5-base/snapshots/c782cba52f8ea6a704240578055cf1c3fc2f2ca9/tokenizer.json
loading file added_tokens.json from cache at None
loading file special_tokens_map.json from cache at /Users/williamzheng/.cache/huggingface/hub/models--google--flan-t5-base/snapshots/c782cba52f8ea6a704240578055cf1c3fc2f2ca9/special_tokens_map.json
loading file tokenizer_config.json from cache at /Users/williamzheng/.cache/huggingface/hub/models--google--flan-t5-base/snapshots/c782cba52f8ea6a704240578055cf1c3fc2f2ca9/tokenizer_config.json
loading configuration file config.json from cache at /Users/williamzheng/.cache/huggingface/hub/models--google--flan-t5-base/snapshots/c782cba52f8ea6a704240578055cf1c3fc2f2ca9/config.json
Model config T

In [258]:
df_train_sample = df_train.head(10).copy()

train_args = {
    'title': 'flan_t5',
    'num_train_epochs' : 50,
    'mlm': False,
    'optimizer': 'adamw_torch',
    'per_device_train_batch_size': 10,
    'per_device_eval_batch_size': 10,
    'warmup_steps': 20,
    'weight_decay': 0.01,
    'logging_steps': 10,
    'save_model': True,
}

# Set training data and targets
x = df_train_sample['question']
y = df_train_sample['answer']

# Train model
lm_flan_train.fit(x, y, train_args, instruct=True)

Map:   0%|          | 0/10 [00:00<?, ? examples/s]

Map:   0%|          | 0/10 [00:00<?, ? examples/s]

PyTorch: setting up devices
The default value for the training argument `--report_to` will change in v5 (from all installed integrations to none). In v5, you will need to use `--report_to all` to get the same behavior as now. You should start updating your code and make this info disappear :-).
***** Running training *****
  Num examples = 10
  Num Epochs = 50
  Instantaneous batch size per device = 10
  Total train batch size (w. parallel, distributed & accumulation) = 10
  Gradient Accumulation steps = 1
  Total optimization steps = 50
  Number of trainable parameters = 247577856
You're using a T5TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.


Setting up training in sequence to sequence format...




Training completed. Do not forget to share your model on huggingface.co/models =)


Saving model checkpoint to ./results/model_flan_t5
Configuration saved in ./results/model_flan_t5/config.json
Configuration saved in ./results/model_flan_t5/generation_config.json
Model weights saved in ./results/model_flan_t5/pytorch_model.bin


In [259]:
lm_flan.predict('What is the meaning of life?')['text']

Generate config GenerationConfig {
  "decoder_start_token_id": 0,
  "eos_token_id": 1,
  "pad_token_id": 0,
  "transformers_version": "4.26.1"
}



'life is a cycle of life'

In [263]:
lm_flan_train.predict('What is the meaning of life?')['text']

Generate config GenerationConfig {
  "decoder_start_token_id": 0,
  "eos_token_id": 1,
  "pad_token_id": 0,
  "transformers_version": "4.26.1"
}



'Life is the meaning of all that comes to you.'